//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NITCOTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetDetail
    {
        public int Id { get; set; }
        public int productId { get; set; }
        public int ResetHeaderId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> soldPrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ResetHeader ResetHeader { get; set; }
    }
}
